= Marionette Architecture

Updated 5-18-2023, v0.1.0

A comprehensive guide to the disassembly architecture provided by Marionette.

== Table of Contents

1. Introduction
a. Dictionary
b. Psuedo Code Notation
2. Requirements for the Marionette Disassembly Architecture
3. The Marionette Disassembly Architecture

== Introduction

The Marionette Disassembly Architecture is a intermediate representation for data extracted from a binary file. These binary files can be generated by different compilers. The Marionette Architecture aims to provide a common interface for disassembling these files. The goal is to accomodate the different compilers and provide a common interface for the data. Therefore allowing tools to be written that can interface with binary data with ease without having to worry about the compiler that generated the binary file.

Currently the Marionette Disassembly Architecture is in the early stages of development. The current version is 0.1.0. The current version is not stable and is subject to change. The current version is not recommended for production use.

It should be noted that the Marionette Disassembly Architecture is not a disassembler. It is an intermediate representation for data extracted from a binary file. The Marionette Disassembly Architecture is not a replacement for a disassembler. It is a common interface for disassemblers to use.

The Marionette Disassembly Architecture was specifically designed to be used with the Marionette Disassembler. The Marionette Disassembler is a disassembler that uses the Marionette Disassembly Architecture as its intermediate representation. The Marionette Disassembler is currently in development and this document will be updated by the author over time. This document is meant to serve as both a guide and a prototyping document for the Marionette Disassembler Architecture.

As of Marionette version 0.1.0, the planned compilers to be supported are:

* Lua [Versions: 5.1]
* Python [Versions: TBD]
* Java [Versions: TBD]

=== Dictionary

* Binary File - A file that contains binary data.

* Binary Data - Data that is represented in binary form.

* Compiler - A program that translates source code into machine code.

* Disassembler - A program that translates machine code into assembly code.

* Intermediate Representation - A representation of data that is used as an intermediate step between two representations.

* Marionette - A disassembler that uses the Marionette Disassembly Architecture as its intermediate representation.

* Marionette Disassembly Architecture - A intermediate representation for data extracted from a binary file.

=== Psuedo Code Notation

In this guide we will be using a psuedo code notation to represent various data structures, functions, and compiler formats. This notation is meant to be a guide and is not meant to be a strict representation of the data. The notation is meant to be a guide to help the reader understand the data structures, functions, and compiler formats.

The notation is as follows:

Pseudo-notation to declare a class is as follows:



== Requirements for the Marionette Disassembly Architecture

Due to the inherit nature of the Marionette Disassembly Architecture, there are some requirements that must be met in order to develop a intermediate representation for a compiler. This is due to multiple compilers having different ways of representing data. The Marionette Disassembly Architecture aims to provide a common interface for these different compilers. Therefore, the Marionette Disassembly Architecture has some requirements for the architecture design.

In order to add a new compiler to the Marionette Disassembly Architecture needs to ensure that the binary representation and meaning is preserved. Meaning that there can be no loss of information between any compiler design and the Marionette Disassembly Architecture.

Going over a few of the compilers that are planned to be supported, we can see that there are some differences in the way that they represent data. For example, Lua uses a stack based virtual machine. This means that the Lua compiler will generate code that is designed to be executed on a stack based virtual machine. This is different from Python and Java. Python and Java both use register based virtual machines. This means that the Python and Java compilers will generate code that is designed to be executed on a register based virtual machine.

Another example is the way methods are represented. Lua has different fields that represent the data for a method. Python and Java have different fields that represent the data for a method. This means that the Marionette Disassembly Architecture needs to be able to represent the data for a method in a way that is common to all compilers.

== The Marionette Disassembly Architecture

The Marionette Disassembly Architecture is a intermediate representation for data extracted from a binary file. The Marionette Disassembly Architecture is designed to be used with the Marionette Disassembler. The Marionette Disassembler is a disassembler that uses the Marionette Disassembly Architecture as its intermediate representation.